### ISSUE TITLE
Can nosnoc determine the state transition borders (gap functions)?

### ISSUE THREAD

**Issue by VasilyRakche** [nurkanovic/nosnoc#29]
Hi,
Thanks for the nice tool and quite interesting research papers. 

I am not sure how to formulate one hybrid dynamics problem in order to solve it with Nosnoc. In simple terms, it is as follows:
```
master; % integer, influences the speed capabilities by switching the profiles 
u; % continuous control

if master==0
    f = profile_0; % define dynamics profile 0
elseif master==1
    f = profile_1; % define dynamics profile 1 
end

% goal: achieve *maximum speed*. 
% Determine best `u` (continuous control) and `master` (profile sequence e.g. profile_0, profile_1, profile_0)

```
I have checked examples, but I start to think you might not be dealing with these cases. I saw that you are defining the gap function. However, in this case the gap function should be kinda determined by the algorithm and it might be changing in time as well. 

Would really appreciate feedback.

Best,

**Comment by nurkanovic** [comment]
Hello,

thanks for your interest in our work. nosnoc cannot determine the gap/switching functions. 
In fact, the switching functions, passed via `model.c` in nosnoc, is a key ingredient in the definition of a nonsmooth dynamical system.
It seems to me, that `master` corresponds to the switching profile, which are the variables `theta` in our code and papers ( the Filippov convex multipliers).
It would be helpful if you can determine what triggers the change of master, which state? 

Best regards,
Armin

**Comment by VasilyRakche** [comment]
Hi Armin,

Thank you for the response! I was trying to find a way to incorporate and define switching functions for this case. Maybe I can try out with defining some additional optimization variable (continuous decision variable) and constraint. Something like:
```
   mu = opti.variable(d);
   opti.subject_to(mu*q == 0);
```

Do you have an example on how to do that with nosnoc?

Best,
Vasilije

**Comment by nurkanovic** [comment]
Hi Vasilije,

If I understand it correctly, you have a problem and want to find out the switching functions.
So far, we have not dealt with this case and assume the switching functions to be known. 
You can pass them to nosnoc via `model.c = c` where `c` is some CasADi expression. 
Mathematically, it might lead to some difficulties because c(x) the switching function depends on other variables than the differential states.
However, when the pending pull request is merged, we will likely have support for having other unknown parameters (which we call `v_global`.  And one will be able to define a switching function that can be optimized. 

But maybe you can provide me with more details on your problem and I can help formulate it possibly within the currently available tools (which are well-tested and understood). You can also write me an e-mail if you like.

Best regards,
Armin
